sajari/search-widgets

- .changeset/famous-moons-watch.md
- src/interface/OverlayInterface.tsx
Re-add the div wrapper that was removed in https://github.com/sajari/search-widgets/pull/218/files#diff-1a119c7a0a2e5d8bf5b64b9342759eaa7fd4d839b3745841b1d085c9f11041aaL155. This caused users won't be able to scroll to view more results on the mobile overlay.
> fix: unable to scroll on mobile overlay

- .changeset/two-ducks-admire.md
- src/interface/TokenCheckBlank.tsx
- src/interface/index.tsx
- src/search-input-binding.tsx
fix: add support for automatic posneg token consumption to overlay mode
> fix: add support for automatic posneg token consumption to overlay mode

- .github/workflows/release.yml
github: send slack notifications on prod builds and rename release pr
> github: send slack notifications on prod builds and rename release pr

- .changeset/twelve-peas-clap.md
- src/defaults.ts
- src/search-input-binding.tsx
- src/search-input.tsx
- yarn.lock
Upgrade the package to fix the issue when users cannot use "enter" to trigger a search.
> chore: update search ui

- .changeset/good-walls-pretend.md
- package.json
- yarn.lock
Upgrade React SDK to include the fix - https://github.com/sajari/sdk-react/pull/741
> fix: result being ignored if having same position with banner

- .github/workflows/release.yml
build: allow changeset created prs to execute github actions
> build: allow changeset created prs to execute github actions

- .changeset/cuddly-buses-relate.md
- src/defaults.ts
https://search-io.atlassian.net/jira/software/projects/SF/boards/29?selectedIssue=SF-781
replace tracking instances witch EventTracking
> fix: transition trackings to EventTracking

- .changeset/shaggy-donkeys-perform.md
- src/interface/OverlayInterface.tsx
- src/interface/StandardInterface.tsx
- src/types/index.ts
There are some places in code that we are still ignoring the incoming `showPoweredBy` prop
Remove the logic so that the incoming prop will go through to the component itself
> fix: respect incoming prop

- cypress/fixtures/banner.json
- cypress/fixtures/promotion.json
- cypress/fixtures/template.txt
- cypress/integration/results.test.ts
- src/interface/OverlayInterface.tsx
- src/interface/StandardInterface.tsx
Resolve https://search-io.atlassian.net/browse/SF-799. Add test cases to cover:
> test: add test cases for results widget

- .changeset/tall-bobcats-beg.md
- cypress/fixtures/search-overlay.json
- cypress/integration/overlay.test.ts
- cypress/support/commands.ts
- src/interface/OverlayInterface.tsx
https://search-io.atlassian.net/jira/software/projects/SF/boards/29?selectedIssue=SF-801
Add more test cases to search overlay
> feat: search overlay tests

- .changeset/healthy-shoes-speak.md
- .gitignore
- cypress/fixtures/autocomplete.json
- cypress/fixtures/search-overlay.json
- cypress/integration/input.test.ts
- cypress/integration/overlay.test.ts
- cypress/support/commands.ts
- package.json
- src/interface/OverlayInterface.tsx
- yarn.lock
https://search-io.atlassian.net/jira/software/projects/SF/boards/29?selectedIssue=SF-798
Add msw as mock service
Add more test cases to search input
Update some scripts for e2e
> feat: search input tests

- .changeset/angry-feet-float.md
- cypress/integration/input.test.ts
- cypress/integration/takeover-input.test.ts
- documentation/configuration-reference.md
- src/search-input-binding.tsx
- src/search-input.tsx
- src/types/index.ts
Resolve https://search-io.atlassian.net/browse/SF-743
> fix: sync url params to search input

- cypress/fixtures/multiple-filters.json
- cypress/integration/filters.test.ts
Resolve https://search-io.atlassian.net/browse/SF-808
> test: add tests for multiple filters

- cypress/integration/input.test.ts
- cypress/integration/overlay.test.ts
- cypress/integration/results.test.ts
- cypress/integration/takeover-input.test.ts
- cypress/support/commands.ts
- package.json
- yarn.lock
https://search-io.atlassian.net/browse/SF-812
- remove `cypress-localstorage-commands`
- clear localStorage afterEach
> fix: make cypress stateless

- cypress/fixtures/list-filter.json
- cypress/integration/filter.test.ts
- cypress/support/commands.ts
https://search-io.atlassian.net/jira/software/projects/SF/boards/29?selectedIssue=SF-804
add more tests for list filter
> feat: list filter tests

- .changeset/empty-ties-tease.md
- cypress/integration/filters.test.ts
- src/hooks/useSearchProviderProps/index.ts
https://search-io.atlassian.net/jira/software/projects/SF/boards/29?selectedIssue=SF-594
Add merge flag to filterBuilder.set, which previously overrode initial value
> fix: initial value is omitted

- cypress/integration/filters.test.ts
This is an example of how we should use a more specific selector in tests per feedback in https://github.com/sajari/search-widgets/pull/290#discussion_r862602049.
> test: simplify test selectors in filters.test

- cypress/fixtures/color-filter.json
- cypress/integration/filters.test.ts
- package.json
- src/interface/StandardInterface.tsx
- yarn.lock
https://search-io.atlassian.net/browse/SF-807
- add test cases for color filter
> feat: color filter tests

- cypress/integration/filters.test.ts
This causes the rest of the filter tests to stall
> test: fix only trigger range filter tests

- .changeset/odd-mice-tie.md
- src/interface/Options/index.tsx
- yarn.lock
https://search-io.atlassian.net/browse/SF-877
https://search-io.atlassian.net/jira/polaris/projects/PD/ideas/view/466633?selectedIssue=PD-117
> lang: use i18n for labels in several overlay widget strings

- .changeset/odd-nails-mix.md
- package.json
- yarn.lock
> fix: improve French translations

- .changeset/gentle-windows-deliver.md
- package.json
- yarn.lock
> fix: upgrade react-search-ui for improved french translations

- .babelrc
- .changeset/giant-terms-jump.md
- .yarnrc.yml
- cypress/integration/filters.test.ts
- package.json
- yarn.lock
feat: upgrade tailwind and adopt latest downstream bug fixes
> feat: upgrade tailwind and adopt latest downstream bug fixes

- cypress/e2e/results.cy.ts
Co-authored-by: beatrice94 <17920228+beatrice94@users.noreply.github.com>
Co-authored-by: wwalser <wwalser@search.io>
> test: add regression test for recent pagination change
